(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const canvas = $('gameCanvas'), ctx = canvas.getContext('2d');
  const W = canvas.width, H = canvas.height, ROAD = { x: 36, width: 288 };
  const State = Object.freeze({ START:'START', PLAYING:'PLAYING', PAUSED:'PAUSED', OVER:'GAME OVER' });
  const game = { state:State.START, score:0, high:Number(localStorage.getItem('princyNeonHighScore') || 0), level:1, lane:1, playerX:180, enemies:[], powerups:[], particles:[], last:0, spawn:0, powerSpawn:0, roadOffset:0, sound:true, audio:null, shield:false, nitroUntil:0, boostUntil:0 };
  $('highScore').textContent = pad(game.high);
  function pad(n){ return String(Math.floor(n)).padStart(6,'0'); }
  function status(text){ $('gameStatus').textContent=text; }
  function beep(freq=440,duration=.08){ if(!game.sound)return; try{game.audio ||= new (window.AudioContext||window.webkitAudioContext)(); const o=game.audio.createOscillator(),g=game.audio.createGain();o.frequency.value=freq;o.type='square';g.gain.value=.035;o.connect(g);g.connect(game.audio.destination);o.start();o.stop(game.audio.currentTime+duration)}catch(e){/* audio is optional */} }
  function setState(next){ game.state=next; $('gameShell').dataset.state=next; $('startScreen').classList.toggle('hidden',next!==State.START); $('pauseScreen').classList.toggle('hidden',next!==State.PAUSED); $('gameOverScreen').classList.toggle('hidden',next!==State.OVER); $('pauseButton').textContent=next===State.PAUSED?'▶ RESUME':'Ⅱ PAUSE'; }
  function startGame(){ game.score=0;game.level=1;game.lane=1;game.playerX=180;game.enemies=[];game.powerups=[];game.particles=[];game.spawn=0;game.powerSpawn=2;game.shield=false;game.nitroUntil=0;game.boostUntil=0;game.last=performance.now();setState(State.PLAYING);beep(620);status('Race started. Dodge the traffic!');requestAnimationFrame(loop); }
  function pause(){ if(game.state===State.PLAYING){setState(State.PAUSED);status('Game paused.');beep(220)}else if(game.state===State.PAUSED){setState(State.PLAYING);game.last=performance.now();status('Back on the highway!');requestAnimationFrame(loop);beep(520)} }
  function move(dir){if(game.state!==State.PLAYING)return;game.lane=Math.max(0,Math.min(2,game.lane+dir));beep(330);}
  function difficulty(){game.level=Math.min(12,1+Math.floor(game.score/500));return {speed:145+game.level*13,interval:Math.max(.42,1.05-game.level*.055)};}
  function spawnEnemy(){const lane=Math.floor(Math.random()*3);game.enemies.push({lane,x:laneCenter(lane),y:-70,w:38,h:66,speed:difficulty().speed*(.82+Math.random()*.3),hue:Math.random()<.5?'#ff2f9d':'#9b5cff',passed:false});}
  function spawnPower(){const types=['shield','nitro','boost'];const lane=Math.floor(Math.random()*3);game.powerups.push({type:types[Math.floor(Math.random()*3)],lane,x:laneCenter(lane),y:-30,size:18});}
  function laneCenter(lane){return ROAD.x+ROAD.width/6+lane*ROAD.width/3;}
  function rectHit(a,b){return Math.abs(a.x-b.x)<(a.w+b.w)/2-5&&Math.abs(a.y-b.y)<(a.h+b.h)/2-6;}
  function collect(p){if(p.type==='shield')game.shield=true;if(p.type==='nitro')game.nitroUntil=performance.now()+6000;if(p.type==='boost')game.boostUntil=performance.now()+7000;beep(880,.14);status(`${p.type.toUpperCase()} collected!`);for(let i=0;i<12;i++)game.particles.push({x:p.x,y:p.y,life:.5,color:'#ffe66d'});}
  function update(dt,now){const d=difficulty();game.roadOffset=(game.roadOffset+d.speed*dt)%80;game.spawn+=dt;game.powerSpawn+=dt;if(game.spawn>d.interval){game.spawn=0;spawnEnemy()}if(game.powerSpawn>7){game.powerSpawn=0;spawnPower()}
    const player={x:game.playerX,y:H-83,w:34,h:60}; game.playerX+=(laneCenter(game.lane)-game.playerX)*Math.min(1,dt*12);
    game.enemies.forEach(e=>{e.y+=e.speed*dt;if(rectHit(player,e)){if(game.shield){game.shield=false;e.y=H+100;beep(760);status('Shield absorbed the impact!')}else{gameOver();return}}if(!e.passed&&e.y>H){e.passed=true;game.score+=50;}});game.enemies=game.enemies.filter(e=>e.y<H+90);
    game.powerups.forEach(p=>{p.y+=d.speed*.82*dt;if(Math.abs(p.x-player.x)<30&&Math.abs(p.y-player.y)<45){collect(p);p.y=H+100}});game.powerups=game.powerups.filter(p=>p.y<H+40);
    game.score+=dt*12*(now<game.boostUntil?2:1);const old=game.level;game.level=difficulty().level;if(game.level>old){beep(740);status(`LEVEL ${game.level} — traffic intensifying!`)}$('score').textContent=pad(game.score);$('level').textContent=game.level;$('powerStatus').textContent=game.shield?'SHIELD':now<game.nitroUntil?'NITRO':now<game.boostUntil?'2X SCORE':'READY';$('powerStatus').className=(game.shield||now<game.nitroUntil||now<game.boostUntil)?'boost':'';
    game.particles.forEach(p=>{p.y+=35*dt;p.life-=dt});game.particles=game.particles.filter(p=>p.life>0);
  }
  function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#050817';ctx.fillRect(0,0,W,H);ctx.fillStyle='#101a32';ctx.fillRect(ROAD.x,0,ROAD.width,H);ctx.strokeStyle='#20f6ff';ctx.lineWidth=3;ctx.strokeRect(ROAD.x,0,ROAD.width,H);ctx.setLineDash([34,46]);ctx.lineWidth=4;ctx.lineDashOffset=game.roadOffset;ctx.strokeStyle='#b9ffff99';[ROAD.x+ROAD.width/3,ROAD.x+ROAD.width*2/3].forEach(x=>{ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()});ctx.setLineDash([]);
    game.enemies.forEach(e=>car(e.x,e.y,e.w,e.h,e.hue));game.powerups.forEach(p=>{ctx.save();ctx.translate(p.x,p.y);ctx.shadowBlur=18;ctx.shadowColor='#ffe66d';ctx.strokeStyle='#ffe66d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,p.size,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#ffe66d';ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.type==='shield'?'S':p.type==='nitro'?'N':'2X',0,0);ctx.restore()});car(game.playerX,H-83,34,60,'#20f6ff');if(game.shield){ctx.strokeStyle='#ffe66d';ctx.lineWidth=3;ctx.shadowBlur=15;ctx.shadowColor='#ffe66d';ctx.beginPath();ctx.arc(game.playerX,H-53,31,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}game.particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4)});ctx.globalAlpha=1;}
  function car(x,y,w,h,color){ctx.save();ctx.translate(x,y);ctx.shadowColor=color;ctx.shadowBlur=16;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,8);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#071021';ctx.fillRect(-w*.32,-h*.22,w*.64,h*.25);ctx.fillStyle='#fff';ctx.fillRect(-w*.38,-h*.4,7,4);ctx.fillRect(w*.2,-h*.4,7,4);ctx.fillStyle='#111';ctx.fillRect(-w/2,-h*.25,5,14);ctx.fillRect(w/2-5,-h*.25,5,14);ctx.restore();}
  function loop(now){if(game.state!==State.PLAYING)return;const dt=Math.min(.05,(now-game.last)/1000);game.last=now;update(dt,now);draw();requestAnimationFrame(loop)}
  function gameOver(){if(game.state===State.OVER)return;setState(State.OVER);if(game.score>game.high){game.high=Math.floor(game.score);localStorage.setItem('princyNeonHighScore',game.high)}$('highScore').textContent=pad(game.high);$('finalScore').textContent=pad(game.score);$('finalHighScore').textContent=pad(game.high);status('Race over. Press Race Again to return to the highway.');beep(110,.3);}
  $('startButton').onclick=startGame;$('raceAgainButton').onclick=startGame;$('pauseRestartButton').onclick=startGame;$('pauseButton').onclick=pause;$('resumeButton').onclick=pause;$('leftButton').onclick=()=>move(-1);$('rightButton').onclick=()=>move(1);$('soundToggle').onclick=()=>{game.sound=!game.sound;$('soundToggle').textContent=game.sound?'🔊 SOUND ON':'🔇 SOUND OFF';$('soundToggle').setAttribute('aria-label',game.sound?'Turn sound off':'Turn sound on');if(game.sound)beep()};
  document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' ','a','d','A','D'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft'||e.key==='a'||e.key==='A')move(-1);if(e.key==='ArrowRight'||e.key==='d'||e.key==='D')move(1);if(e.key===' ')pause()});
  draw();
})();
